apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5000
